version: 3

dotenv:
  - .env

tasks:
  # Install dependencies
  install:
    desc: Install all dependencies
    cmds:
      - pip install -r requirements/pip.txt
      - ansible-galaxy install -r requirements/ansible.yml

  # Validate configuration
  validate:
    desc: Validate the Ansible playbooks
    deps:
      - install
    cmds:
      - ansible-lint
      - ansible-playbook --syntax-check main.yml

  # Deploy to an environment
  deploy:
    desc: Configure Proxmox cluster in specified environment
    deps:
      - install
    vars:
      INVENTORY: 'inventories/{{ .INVENTORY | default "proxmox" }}.yml'
    cmds:
      - >-
        ansible-playbook
        -i {{ .INVENTORY }}
        --vault-password-file .vault-pass
        main.yml
