version: 3

dotenv:
  - .env

tasks:
  # Install dependencies
  install:
    desc: Install all dependencies
    cmds:
      - ansible-galaxy install -r requirements.yml

  # Deploy to an environment
  deploy:
    desc: Configure Proxmox cluster in specified environment
    deps:
      - install
    vars:
      ENV: '{{ .ENV | default "dev" }}'
      INVENTORY_ARG: |
        {{- if eq .ENV "dev" -}}
        {{- else -}}
          -i inventories/proxmox.yml
        {{- end -}}
    cmds:
      - >-
        ansible-playbook
        {{ .INVENTORY_ARG }}
        --vault-password-file .vault-pass
        main.yml
